import Head from 'next/head'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import { Box, Button, TextField, Typography } from '@mui/material'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Clase 10 - MUI</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <Typography variant="h1" component="h1" className={inter.className}>
          Clase 10: Introduccion a Material UI
        </Typography>
        <Typography variant="h2">Responsive h3</Typography>
        <Box sx={{
          padding: {
            xs: 2,
            sm: 4,
            md: 6,
            lg: 8,
            xl: 10
          },
          border: '1px solid #ccc',
        }}>
          <Button variant="text" size="medium">Text</Button>
          <Button variant="contained">Contained</Button>
          <Button variant="outlined">Outlined</Button>
          <TextField id="outlined-basic" label="Outlined" variant="outlined" />
        </Box>
      </main>
    </>
  )
}
