import Head from 'next/head'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import { Button, Stack, Typography } from '@mui/material'
import Link from 'next/link'
import FormComplejo from '@/components/FormComplejo/FormComplejo'
import { FormProvider, useForm } from 'react-hook-form'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const methods = useForm()
  return (
    <>
      <Head>
        <title>Clase 13</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <Stack spacing={2} direction={'row'}>
          <Link href="/controller">
            <Button variant="outlined" size="small" >
              Controller
            </Button>
          </Link>
          <Link href="/use-controller">
            <Button variant="contained" size="small" >
              useController
            </Button>
          </Link>
          <Link href="/schema">
            <Button variant="outlined" size="small" >
              Schema
            </Button>
          </Link>
        </Stack>
        <Typography variant="h1" component="h1" sx={{ fontSize: 36 }} className={inter.className}>
          Clase 13: React Hook Form + Material UI (UseController hook)
        </Typography>
        <FormProvider {...methods}>
          <FormComplejo />
        </FormProvider>
      </main>
    </>
  )
}
